spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/stackoverflow?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Seoul&useSSL=true
    username: ${MYSQLUSERNAME}
    password: ${MYSQLPASSWORD}

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  key: ${JWT_SECRET_KEY}